#!/usr/bin/env bash
#
# Title: <FILENAME>
# Descr: 
# Date : <DATE>
# Ver  : 1.0

source "$HOME/bin/common.sh"

# BINDIR=$(readlink -f "$(dirname "$0")")

declare commit
declare verbose

args=$(getopt -o vc --long commit,verbose -n "$(basename "$0")" -a -- "$@")

eval set -- "${args}"
  while :
  do
    case "$1" in
      -c | --commit)  commit=1;  shift 1;;
      -v | --verbose) verbose=1; shift 1;;
      --) shift; break ;;
      *) echo "Unexpected option: $1"
    esac
  done

# Implementation here

